import {integer,real,sqliteTable,text} from 'drizzle-orm/sqlite-core';
export const jobTypes=sqliteTable('job_types',{id:integer('id').primaryKey({autoIncrement:true}),name:text('name').notNull().unique(),active:integer('active',{mode:'boolean'}).notNull().default(true)});
export const services=sqliteTable('services',{id:integer('id').primaryKey({autoIncrement:true}),name:text('name').notNull(),code:text('code').notNull().unique(),defaultPrice:real('default_price').notNull().default(0),active:integer('active',{mode:'boolean'}).notNull().default(true)});
export const staff=sqliteTable('staff',{id:integer('id').primaryKey({autoIncrement:true}),name:text('name').notNull(),role:text('role').notNull(),phone:text('phone'),baseSalary:real('base_salary').notNull().default(0),active:integer('active',{mode:'boolean'}).notNull().default(true)});
export const jobs=sqliteTable('jobs',{id:integer('id').primaryKey({autoIncrement:true}),jobNo:text('job_no').notNull().unique(),customerName:text('customer_name').notNull(),phone:text('phone'),location:text('location'),jobTypeId:integer('job_type_id').references(()=>jobTypes.id),serviceId:integer('service_id').references(()=>services.id),description:text('description'),scheduledAt:text('scheduled_at'),status:text('status').notNull().default('new'),quotedAmount:real('quoted_amount').notNull().default(0),createdAt:text('created_at').notNull()});
export const jobStaff=sqliteTable('job_staff',{id:integer('id').primaryKey({autoIncrement:true}),jobId:integer('job_id').notNull().references(()=>jobs.id),staffId:integer('staff_id').notNull().references(()=>staff.id),commission:real('commission').notNull().default(0)});
export const transactions=sqliteTable('transactions',{id:integer('id').primaryKey({autoIncrement:true}),jobId:integer('job_id').references(()=>jobs.id),staffId:integer('staff_id').references(()=>staff.id),date:text('date').notNull(),kind:text('kind').notNull(),category:text('category').notNull(),paymentMethod:text('payment_method').notNull(),amount:real('amount').notNull(),reference:text('reference'),notes:text('notes'),handoverStatus:text('handover_status')});
export const salaryPayments=sqliteTable('salary_payments',{id:integer('id').primaryKey({autoIncrement:true}),staffId:integer('staff_id').notNull().references(()=>staff.id),period:text('period').notNull(),kind:text('kind').notNull(),amount:real('amount').notNull(),paidAt:text('paid_at').notNull(),paymentMethod:text('payment_method').notNull(),notes:text('notes')});
export const appState=sqliteTable('app_state',{id:integer('id').primaryKey(),payload:text('payload').notNull(),updatedAt:text('updated_at').notNull()});
